### ISSUE TITLE
CRITICAL: An exception has been thrown during the rendering of a template ("Error while trying to download (code: 400)

### ISSUE THREAD

**Issue by captainandy14** [mikahanninen/grav-plugin-facebook#48]
Trying to add facebook plugin in the sidebar throws 

grav.CRITICAL: An exception has been thrown during the rendering of a template ("Error while trying to download (code: 400)

adding the error log below..how to fix?

`[2019-03-22 15:03:52] grav.CRITICAL: An exception has been thrown during the rendering of a template ("Error while trying to download (code: 400): https://graph.facebook.com/1071517943003802/?fields=feed{permalink_url,created_time,link,attachments,message}&access_token=|  ") in "@Page:C:/inetpub/wwwroot/blogs.exaiimsdoctors.com/user/pages/sidebar" at line 4. - Trace: #0 C:\inetpub\wwwroot\blogs.exaiimsdoctors.com\vendor\twig\twig\lib\Twig\Template.php(399): Twig_Template->displayWithErrorHandling(Array, Array) #1 C:\inetpub\wwwroot\blogs.exaiimsdoctors.com\vendor\twig\twig\lib\Twig\Template.php(407): Twig_Template->display(Array) #2 C:\inetpub\wwwroot\blogs.exaiimsdoctors.com\vendor\twig\twig\lib\Twig\Environment.php(363): Twig_Template->render(Array) #3 C:\inetpub\wwwroot\blogs.exaiimsdoctors.com\system\src\Grav\Common\Twig\Twig.php(280): Twig_Environment->render('@Page:C:/inetpu...', Array) #4 C:\inetpub\wwwroot\blogs.exaiimsdoctors.com\system\src\Grav\Common\Page\Page.php(789): Grav\Common\Twig\Twig->processPage(Object(Grav\Common\Page\Page), '<h4>Our Tweets<...') #5 C:\inetpub\wwwroot\blogs.exaiimsdoctors.com\system\src\Grav\Common\Page\Page.php(672): Grav\Common\Page\Page->processTwig() #6 C:\inetpub\wwwroot\blogs.exaiimsdoctors.com\vendor\twig\twig\lib\Twig\Template.php(673): Grav\Common\Page\Page->content() #7 C:\inetpub\wwwroot\blogs.exaiimsdoctors.com\cache\twig\6d\6d839da84731b50f0a585ccf0dcee4bf403563ee71378693c1331fd5644b799f.php(28): Twig_Template->getAttribute(Object(Grav\Common\Page\Page), 'content', Array) #8 C:\inetpub\wwwroot\blogs.exaiimsdoctors.com\vendor\twig\twig\lib\Twig\Template.php(428): __TwigTemplate_4c971526b6535dfd4d54a24da9889bf78351ceb755a22db67f55623e5ae242f3->doDisplay(Array, Array) #9 C:\inetpub\wwwroot\blogs.exaiimsdoctors.com\vendor\twig\twig\lib\Twig\Template.php(399): Twig_Template->displayWithErrorHandling(Array, Array) #10 C:\inetpub\wwwroot\blogs.exaiimsdoctors.com\cache\twig\22\22174f29bf11f4ae8e44376e941ac7ab03a88f0088a6b61001e77b8ba5ad483c.php(450): Twig_Template->display(Array) #11 C:\inetpub\wwwroot\blogs.exaiimsdoctors.com\vendor\twig\twig\lib\Twig\Template.php(215): __TwigTemplate_69d804f063d4faf754bac85f5272f7bd9cc2717c0f0386f7b5b0fe3534f839df_755067330->block_sidebar(Array, Array) #12 C:\inetpub\wwwroot\blogs.exaiimsdoctors.com\cache\twig\cc\ccb37d0810ca6b1bf81bb6e8936a3e2fdb513dee12edf096c060ee812311f97d.php(61): Twig_Template->displayBlock('sidebar', Array, Array) #13 C:\inetpub\wwwroot\blogs.exaiimsdoctors.com\vendor\twig\twig\lib\Twig\Template.php(428): __TwigTemplate_bb1fe3a2394ae7d69a6fd2ccb19cf39258d17950ed280e207b6d5b1a4de9dae3->doDisplay(Array, Array) #14 C:\inetpub\wwwroot\blogs.exaiimsdoctors.com\vendor\twig\twig\lib\Twig\Template.php(399): Twig_Template->displayWithErrorHandling(Array, Array) #15 C:\inetpub\wwwroot\blogs.exaiimsdoctors.com\cache\twig\22\22174f29bf11f4ae8e44376e941ac7ab03a88f0088a6b61001e77b8ba5ad483c.php(298): Twig_Template->display(Array, Array) #16 C:\inetpub\wwwroot\blogs.exaiimsdoctors.com\vendor\twig\twig\lib\Twig\Template.php(428): __TwigTemplate_69d804f063d4faf754bac85f5272f7bd9cc2717c0f0386f7b5b0fe3534f839df_755067330->doDisplay(Array, Array) #17 C:\inetpub\wwwroot\blogs.exaiimsdoctors.com\vendor\twig\twig\lib\Twig\Template.php(399): Twig_Template->displayWithErrorHandling(Array, Array) #18 C:\inetpub\wwwroot\blogs.exaiimsdoctors.com\cache\twig\22\22174f29bf11f4ae8e44376e941ac7ab03a88f0088a6b61001e77b8ba5ad483c.php(120): Twig_Template->display(Array) #19 C:\inetpub\wwwroot\blogs.exaiimsdoctors.com\vendor\twig\twig\lib\Twig\Template.php(215): __TwigTemplate_69d804f063d4faf754bac85f5272f7bd9cc2717c0f0386f7b5b0fe3534f839df->block_body(Array, Array) #20 C:\inetpub\wwwroot\blogs.exaiimsdoctors.com\cache\twig\57\57e0a755e295a1a444bdf3a6723636b9499dff5c4e95d315319288397f4db2f0.php(84): Twig_Template->displayBlock('body', Array, Array) #21 C:\inetpub\wwwroot\blogs.exaiimsdoctors.com\vendor\twig\twig\lib\Twig\Template.php(428): __TwigTemplate_ea76a5140239521276a9b9913a7e64a44386fdbf271f368a775b7666ca59d8b5->doDisplay(Array, Array) #22 C:\inetpub\wwwroot\blogs.exaiimsdoctors.com\vendor\twig\twig\lib\Twig\Template.php(399): Twig_Template->displayWithErrorHandling(Array, Array) #23 C:\inetpub\wwwroot\blogs.exaiimsdoctors.com\cache\twig\22\22174f29bf11f4ae8e44376e941ac7ab03a88f0088a6b61001e77b8ba5ad483c.php(59): Twig_Template->display(Array, Array) #24 C:\inetpub\wwwroot\blogs.exaiimsdoctors.com\vendor\twig\twig\lib\Twig\Template.php(428): __TwigTemplate_69d804f063d4faf754bac85f5272f7bd9cc2717c0f0386f7b5b0fe3534f839df->doDisplay(Array, Array) #25 C:\inetpub\wwwroot\blogs.exaiimsdoctors.com\vendor\twig\twig\lib\Twig\Template.php(399): Twig_Template->displayWithErrorHandling(Array, Array) #26 C:\inetpub\wwwroot\blogs.exaiimsdoctors.com\vendor\twig\twig\lib\Twig\Template.php(407): Twig_Template->display(Array) #27 C:\inetpub\wwwroot\blogs.exaiimsdoctors.com\vendor\twig\twig\lib\Twig\Environment.php(363): Twig_Template->render(Array) #28 C:\inetpub\wwwroot\blogs.exaiimsdoctors.com\system\src\Grav\Common\Twig\Twig.php(380): Twig_Environment->render('blog.html.twig', Array) #29 C:\inetpub\wwwroot\blogs.exaiimsdoctors.com\system\src\Grav\Common\Service\OutputServiceProvider.php(27): Grav\Common\Twig\Twig->processSite('html') #30 C:\inetpub\wwwroot\blogs.exaiimsdoctors.com\vendor\pimple\pimple\src\Pimple\Container.php(118): Grav\Common\Service\OutputServiceProvider->Grav\Common\Service\{closure}(Object(Grav\Common\Grav)) #31 C:\inetpub\wwwroot\blogs.exaiimsdoctors.com\system\src\Grav\Common\Processors\RenderProcessor.php(19): Pimple\Container->offsetGet('output') #32 C:\inetpub\wwwroot\blogs.exaiimsdoctors.com\system\src\Grav\Common\Grav.php(131): Grav\Common\Processors\RenderProcessor->process() #33 C:\inetpub\wwwroot\blogs.exaiimsdoctors.com\system\src\Grav\Common\Grav.php(370): Grav\Common\Grav->Grav\Common\{closure}() #34 [internal function]: Grav\Common\Grav::Grav\Common\{closure}('render', 'Render', Object(Closure)) #35 C:\inetpub\wwwroot\blogs.exaiimsdoctors.com\system\src\Grav\Common\Grav.php(346): call_user_func_array(Object(Closure), Array) #36 C:\inetpub\wwwroot\blogs.exaiimsdoctors.com\system\src\Grav\Common\Grav.php(132): Grav\Common\Grav->__call('measureTime', Array) #37 C:\inetpub\wwwroot\blogs.exaiimsdoctors.com\index.php(54): Grav\Common\Grav->process() #38 {main} [] []`

**Comment by davidpipes** [comment]
I too am getting a similar error. 

"""
An exception has been thrown during the rendering of a template ("Error while trying to download (code: 400): https://graph.facebook.com/183195242039812/?fields ▶
") in "@Page:/home/underpr1/public_html/dev/user/pages/01.home/03._guarantee" at line 13.
"""

**Comment by mikahanninen** [comment]
Hopefully release 1.7.1 will fix your problem. You have entered Application ID and secret into Facebook plugin settings ?

**Comment by davidpipes** [comment]
Yep, I'll give it a try once 1.7.1 is released. I think the new Facebook review process might be my next hurdle in using this as well.

**Comment by mikahanninen** [comment]
The posts can be received without any additional steps (review process or what not) at least for my existing site where I am using this plugin but events & albums are not working without additional effort with Facebook.

**Comment by plant7403** [comment]
<img width="860" alt="Capture" src="https://user-images.githubusercontent.com/24483751/57950022-3eb50880-7910-11e9-91ef-5700fd392a1b.PNG">

fixed, or i do something wrong? 😂
